/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NodeTECH;

public class App {
    public String getGreeting() {
        return "打首獄門同好会";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
